version: '3'

services:
  # Add your services here, default image is netsos/rhit-netsec:latest
  #
  # Make sure to sync volumes using the following.
  # volumes:
  #   - ./volumes:/volumes
  #
  # Run the config script.
  # command:
  #   bash -c "bash /volmes/check_config.sh && tail -f /dev/null"
  #

  #
  # Internet (outside world)
  #
  noureddi-client:
    image: netsos/rhit-netsec:fw
    container_name: noureddi-client
    hostname: noureddi-client
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes/:/volumes
    networks:
      noureddi-subnet1:
        ipv4_address: 10.10.0.4
    extra_hosts:
      noureddi-server: "10.10.1.4"
    command: bash -c "
              bash /volumes/check_config.sh &&
              ip route add 10.10.1.0/24 dev eth0 via 10.10.0.10 &&
              tail -f /dev/null
            "

  #
  # Firewall sits at the boundary
  #
  noureddi-firewall:
    image: netsos/rhit-netsec:fw
    container_name: noureddi-firewall
    hostname: noureddi-firewall
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes/:/volumes
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      noureddi-subnet1:
        ipv4_address: 10.10.0.10
      noureddi-subnet2:
        ipv4_address: 10.10.1.10
    command: bash -c "
                bash /volumes/check_config.sh &&
                tail -f /dev/null
            "

  #
  # http noureddi-server running telnet and sshd as well
  #
  noureddi-server:
    image: netsos/rhit-netsec:fw
    container_name: noureddi-server
    hostname: noureddi-server
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes/:/volumes
    networks:
      noureddi-subnet2:
        ipv4_address: 10.10.1.4
    extra_hosts:
      noureddi-client: "10.10.0.4"
    command: bash -c "
                bash /volumes/check_config.sh &&
                bash /volumes/setup_telnetd.sh &&
                ip route add 10.10.0.0/24 dev eth0 via 10.10.1.10 &&
                tail -f /dev/null
             "

networks:
  noureddi-subnet1:
    name: noureddi-subnet1
    ipam:
      config:
        - subnet: 10.10.0.0/24
  noureddi-subnet2:
    name: noureddi-subnet2
    ipam:
      config:
        - subnet: 10.10.1.0/24

